/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package net.colar.netbeans.fan;

import java.io.File;
import java.io.PrintWriter;

/**
 * Takes the Antlr generated token list,
 * and create a java file from them, containing TokenID's
 * @author thibautc
 */
public class AntlrTokensToNetbeans {

    public static void main(String[] args)
    {
	if(args.length<3)
	{
	    System.err.println("Need to pass 3 args:");
	    System.err.println("1: The path to the ANTLR token file");
	    System.err.println("2: The path to the java file to output.");
	    System.err.println("3: The package Name to generate in the java file.");
	    System.err.println("Ex: java AntlTokensToNetbeans fan.tokens src/comp/toto/Tokens.java comp.toto");
	    System.exit(-1);
	}
	String tokenFile=args[0];
	String javaFile=args[1];
	String pack=args[2];

	PrintWriter pw=new PrintWriter(new File(javaFile));
	writeHeader(pw,pack);
	writeTokens(pw,tokenFile);
	writeTrailer(pw);
	pw.close();
    }

    private static void writeHeader(PrintWriter pw, String pack, String className)
    {
	pw.println("/*Automatically generated by AntlrTokensToNetbeans.java*/\n");
	pw.println("package "+pack+";");
	pw.println("");
	pw.println("import java.util.Vector;");
	pw.println("");
	pw.println("public class "+className+"{");
	pw.println("");
	pw.println("private static Vector tokens;");
	pw.println("");
	pw.println("static{ // initializes tokens");
    }

    private static void writeTrailer(PrintWriter pw)
    {
	pw.println("	}");
	pw.println("");
	pw.println("	public static Vector getTokens() {return tokens; }");
	pw.println("");
	pw.println("}");
    }

    private static void writeTokens(PrintWriter pw, String tokenFile)
    {
	File f=new File(tokenFile);
	if(f.exists())
	{
	    pw.println("    //Generated from ANTLR tokens: "+tokenFile+"\n");

	}
	else
	{
	    pw.println("    // Missing token file ! : "+f.getAbsolutePath());
	}
    }




}
