/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FanAddMethodDialog.java
 *
 * Created on 9-Dec-2010, 2:31:34 PM
 */
package net.colar.netbeans.fan.hints;

import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import net.colar.netbeans.fan.FanUtilities;
import net.colar.netbeans.fan.parboiled.AstKind;
import net.colar.netbeans.fan.parboiled.AstNode;
import net.colar.netbeans.fan.parboiled.FanLexAstUtils;
import net.colar.netbeans.fan.parboiled.pred.NodeKindPredicate;
import org.netbeans.editor.BaseDocument;
import org.netbeans.modules.editor.indent.api.IndentUtils;

/**
 * Dialog for "Add a method" hint fix.
 * @author thibautc
 */
public class FanAddMethodDialog extends javax.swing.JDialog
{

    private final AstNode node;

    /** Creates new form FanAddFieldDialog */
    public FanAddMethodDialog(java.awt.Frame parent, AstNode node, String varName)
    {
        super(parent, true);
        initComponents();
        nameField.setText(varName);
        this.node = node;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        paramsLbl = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        typeField = new javax.swing.JTextField();
        paramsField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        modifsField = new javax.swing.JTextField();
        modifsLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nameLbl.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.nameLbl.text")); // NOI18N

        typeLbl.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.typeLbl.text")); // NOI18N

        paramsLbl.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.paramsLbl.text")); // NOI18N

        nameField.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.nameField.text")); // NOI18N

        typeField.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.typeField.text")); // NOI18N
        typeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFieldActionPerformed(evt);
            }
        });

        paramsField.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.paramsField.text")); // NOI18N

        cancelButton.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        submitButton.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.submitButton.text")); // NOI18N
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        modifsField.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.modifsField.text")); // NOI18N

        modifsLbl.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.modifsLbl.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl)
                            .addComponent(typeLbl)
                            .addComponent(paramsLbl)
                            .addComponent(modifsLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paramsField)
                            .addComponent(typeField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(modifsField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(submitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLbl)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramsLbl)
                    .addComponent(paramsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifsLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(submitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_typeFieldActionPerformed
    {//GEN-HEADEREND:event_typeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_submitButtonActionPerformed
    {//GEN-HEADEREND:event_submitButtonActionPerformed
        setVisible(false);
        dispose();

        Document doc = node.getRoot().getParserTask().getDocument();

        String str = (modifsField.getText().isEmpty() ? "" : modifsField.getText() + " ")
                + typeField.getText() + " "
                + nameField.getText() + "("
                + paramsField.getText()
                + ") { IMPLEMENT_ME }";

        AstNode slotNode = FanLexAstUtils.findParentNode(node, AstKind.AST_METHOD_DEF);
        if (slotNode == null)
        {
            slotNode = FanLexAstUtils.findParentNode(node, AstKind.AST_CTOR_DEF);
        }

        try
        {
            // if we are in a ctor or method, just create the new method rigth before it
            if (slotNode != null)
            {
                // (should always be 1*indentSize)
                String indentStr = IndentUtils.createIndentString(doc, IndentUtils.indentLevelSize(doc));
                doc.insertString(slotNode.getStartLocation().getIndex(), str + "\n\n" + indentStr, null);
                return;
            } else
            {
                AstNode typeNode = FanLexAstUtils.findParentNode(node, AstKind.AST_TYPE_DEF);
                if (typeNode != null)
                {
                    // Otherwise add at top of type block (after bracket)
                    AstNode blockNode = FanLexAstUtils.getFirstChildRecursive(typeNode, new NodeKindPredicate(AstKind.AST_BLOCK));
                    if (blockNode != null)
                    {
                        // should always be 1*indentSize
                        String indentStr = IndentUtils.createIndentString(doc, IndentUtils.indentLevelSize(doc));
                        doc.insertString(blockNode.getStartLocation().getIndex() + 1, "\n" + indentStr + str, null);
                    }
                }
            }
        } catch (BadLocationException e)
        {
            FanUtilities.GENERIC_LOGGER.exception("BadLocation", e);
        }

    }//GEN-LAST:event_submitButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField modifsField;
    private javax.swing.JLabel modifsLbl;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField paramsField;
    private javax.swing.JLabel paramsLbl;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField typeField;
    private javax.swing.JLabel typeLbl;
    // End of variables declaration//GEN-END:variables
}
