/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FanAddMethodDialog.java
 *
 * Created on 9-Dec-2010, 2:31:34 PM
 */
package net.colar.netbeans.fan.hints;

import java.io.File;
import java.util.HashMap;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import net.colar.netbeans.fan.FanParserTask;
import net.colar.netbeans.fan.FanUtilities;
import net.colar.netbeans.fan.NBFanParser;
import net.colar.netbeans.fan.editor.FantomIndentUtils;
import net.colar.netbeans.fan.indexer.model.FanDocument;
import net.colar.netbeans.fan.parboiled.AstKind;
import net.colar.netbeans.fan.parboiled.AstNode;
import net.colar.netbeans.fan.parboiled.FanLexAstUtils;
import net.colar.netbeans.fan.parboiled.pred.NodeKindPredicate;
import net.colar.netbeans.fan.scope.FanTypeScopeVar;
import net.colar.netbeans.fan.types.FanResolvedType;
import org.netbeans.modules.csl.api.UiUtils;
import org.netbeans.modules.parsing.api.Snapshot;
import org.netbeans.modules.parsing.api.Source;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;

/**
 * Dialog for "Add a method" hint fix.
 * @author thibautc
 */
public class FanAddMethodDialog extends javax.swing.JDialog
{

    private final FanResolvedType targetType;

    /** Creates new form FanAddFieldDialog */
    public FanAddMethodDialog(java.awt.Frame parent, String varName, FanResolvedType targetType, FanResolvedType assignedTo, HashMap<String, FanResolvedType> args)
    {
        super(parent, true);
        initComponents();
        nameField.setText(varName);
        this.targetType = targetType;
        if (assignedTo != null && assignedTo.isResolved())
        {
            typeField.setText(assignedTo.getDbType().getSimpleName());
        }
        if (args != null)
        {
            String params = "";
            for (String key : args.keySet())
            {
                if (params.length() > 0)
                {
                    params += ", ";
                }
                params += args.get(key).getDbType().getSimpleName() + " " + key;
            }
            paramsField.setText(params);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        paramsLbl = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        typeField = new javax.swing.JTextField();
        paramsField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        modifsField = new javax.swing.JTextField();
        modifsLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nameLbl.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.nameLbl.text")); // NOI18N

        typeLbl.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.typeLbl.text")); // NOI18N

        paramsLbl.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.paramsLbl.text")); // NOI18N

        nameField.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.nameField.text")); // NOI18N

        typeField.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.typeField.text")); // NOI18N
        typeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFieldActionPerformed(evt);
            }
        });

        paramsField.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.paramsField.text")); // NOI18N

        cancelButton.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        submitButton.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.submitButton.text")); // NOI18N
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        modifsField.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.modifsField.text")); // NOI18N

        modifsLbl.setText(org.openide.util.NbBundle.getMessage(FanAddMethodDialog.class, "FanAddMethodDialog.modifsLbl.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl)
                            .addComponent(typeLbl)
                            .addComponent(paramsLbl)
                            .addComponent(modifsLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paramsField)
                            .addComponent(typeField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(modifsField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(submitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLbl)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramsLbl)
                    .addComponent(paramsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifsLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(submitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_typeFieldActionPerformed
    {//GEN-HEADEREND:event_typeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_submitButtonActionPerformed
    {//GEN-HEADEREND:event_submitButtonActionPerformed
        Long docId = targetType.getDbType().getSrcDocId();
        FanDocument doc = FanDocument.findById(docId);
        if (doc != null)
        {
            FileObject fo = FileUtil.toFileObject(FileUtil.normalizeFile(new File(doc.getPath())));
            Source source = Source.create(fo);
            Snapshot snapshot = source.createSnapshot();
            // Parse the snaphot
            NBFanParser parser = new NBFanParser();
            try
            {
                parser.parse(snapshot, true);
            } catch (Throwable e)
            {
                return;
            }

            FanParserTask fanResult = (FanParserTask) parser.getResult();
            AstNode rootScope = fanResult.getRootScope();

            FanTypeScopeVar typeVar = FanLexAstUtils.findTypeVar(rootScope, targetType.getDbType().getSimpleName());
            try
            {
                if (typeVar != null)
                {
                    // Otherwise add at top of type block (after bracket)
                    AstNode blockNode = FanLexAstUtils.getFirstChildRecursive(typeVar.getNode(), new NodeKindPredicate(AstKind.AST_BLOCK));
                    if (blockNode != null)
                    {

                        String str = (modifsField.getText().isEmpty() ? "" : modifsField.getText() + " ")
                                + typeField.getText() + " "
                                + nameField.getText() + "("
                                + paramsField.getText()
                                + ") { IMPLEMENT_ME }";


                        Document baseDoc = source.getDocument(true);
                        // should always be 1*indentSize
                        String indentStr = FantomIndentUtils.createIndentString(baseDoc, FantomIndentUtils.getIndentSize(baseDoc));
                        baseDoc.insertString(blockNode.getStartIndex() + 1, "\n" + indentStr + str+"\n", null);
                        // Put the cursor there (open the file if necessary)
                        UiUtils.open(fo, blockNode.getStartIndex()+1);
                    }
                }
            } catch (BadLocationException e)
            {
                FanUtilities.GENERIC_LOGGER.exception("BadLocation", e);
            }
        }

        setVisible(false);
        dispose();
    }//GEN-LAST:event_submitButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField modifsField;
    private javax.swing.JLabel modifsLbl;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField paramsField;
    private javax.swing.JLabel paramsLbl;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField typeField;
    private javax.swing.JLabel typeLbl;
    // End of variables declaration//GEN-END:variables
}
