/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FanCreateTypeDialog.java
 *
 * Created on 9-Dec-2010, 10:29:49 AM
 */
package net.colar.netbeans.fan.hints;

import java.io.File;
import javax.swing.JFileChooser;
import net.colar.netbeans.fan.FanUtilities;
import net.colar.netbeans.fan.templates.TemplateUtils;
import net.colar.netbeans.fan.templates.TemplateView;
import net.jot.web.views.JOTLightweightView;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;

/**
 * Modal dialog to create a new type
 * @author thibautc
 */
public class FanCreateTypeDialog extends javax.swing.JDialog
{

    private JFileChooser chooser;

    /** Creates new form FanCreateTypeDialog */
    public FanCreateTypeDialog(java.awt.Frame parent, String folder, String name)
    {
        super(parent, true);
        initComponents();
        chooser = new JFileChooser(folder);
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setApproveButtonText("Select");
        nameField.setText(name);
        folderField.setText(folder);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        folderLbl = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox();
        nameField = new javax.swing.JTextField();
        folderField = new javax.swing.JTextField();
        Create = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        browseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nameLbl.setText(org.openide.util.NbBundle.getMessage(FanCreateTypeDialog.class, "FanCreateTypeDialog.nameLbl.text")); // NOI18N

        typeLbl.setText(org.openide.util.NbBundle.getMessage(FanCreateTypeDialog.class, "FanCreateTypeDialog.typeLbl.text")); // NOI18N

        folderLbl.setText(org.openide.util.NbBundle.getMessage(FanCreateTypeDialog.class, "FanCreateTypeDialog.folderLbl.text")); // NOI18N

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Class", "Mixin", "Enum" }));

        nameField.setText(org.openide.util.NbBundle.getMessage(FanCreateTypeDialog.class, "FanCreateTypeDialog.nameField.text")); // NOI18N

        folderField.setText(org.openide.util.NbBundle.getMessage(FanCreateTypeDialog.class, "FanCreateTypeDialog.folderField.text")); // NOI18N

        Create.setText(org.openide.util.NbBundle.getMessage(FanCreateTypeDialog.class, "FanCreateTypeDialog.Create.text")); // NOI18N
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        Cancel.setText(org.openide.util.NbBundle.getMessage(FanCreateTypeDialog.class, "FanCreateTypeDialog.Cancel.text")); // NOI18N
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        browseButton.setText(org.openide.util.NbBundle.getMessage(FanCreateTypeDialog.class, "FanCreateTypeDialog.browseButton.text")); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLbl)
                            .addComponent(folderLbl)
                            .addComponent(nameLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(typeCombo, 0, 235, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(folderField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(browseButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                        .addComponent(Create)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLbl)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(folderLbl)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Create)
                    .addComponent(Cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelActionPerformed
    {//GEN-HEADEREND:event_CancelActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CreateActionPerformed
    {//GEN-HEADEREND:event_CreateActionPerformed
        setVisible(false);
        dispose();

        FileObject template = FileUtil.getConfigFile("Templates/Fantom/FantomFile");

        String dir = folderField.getText();
        String name = nameField.getText();
        int combo = typeCombo.getSelectedIndex();

        File newFile = FileUtil.normalizeFile(new File(dir + File.separator + name + ".fan"));

        // create file folder
        File folder = new File(dir);
        folder.mkdirs();

        if (folder.exists() && folder.isDirectory())
        {
            JOTLightweightView view = new TemplateView(template, name);

            switch (combo)
            {
                case 0: // class
                    view.addVariable("doClass", Boolean.TRUE);
                    break;
                case 1: //mixin
                    view.addVariable("doMixin", Boolean.TRUE);
                    break;
                case 2:// enum
                    view.addVariable("doEnum", Boolean.TRUE);
                    break;
            }

            try
            {
                FileObject license = FanUtilities.getRelativeFileObject(template, "../Licenses/FanDefaultLicense.txt");
                view.addVariable("license", license.asText());

                String templateText = template.asText();

                TemplateUtils.createFromTemplate(view, templateText, newFile);

                FanUtilities.openFileInEditor(newFile);
                // Note: refresh the parent folder, otherwise it lags
                FileUtil.refreshFor(newFile.getParentFile());
            } catch (Exception e)
            {
                FanUtilities.GENERIC_LOGGER.exception("Failed creating new type", e);
            }
        }
    }//GEN-LAST:event_CreateActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_browseButtonActionPerformed
    {//GEN-HEADEREND:event_browseButtonActionPerformed
        int val = chooser.showDialog(this, "Select");
        if (val == JFileChooser.APPROVE_OPTION)
        {
            folderField.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Create;
    private javax.swing.JButton browseButton;
    private javax.swing.JTextField folderField;
    private javax.swing.JLabel folderLbl;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JComboBox typeCombo;
    private javax.swing.JLabel typeLbl;
    // End of variables declaration//GEN-END:variables
}
