/*
 * Thibaut Colar Aug 13, 2009
 */

/*
 * FanProjectPropertiesPanel.java
 *
 * Created on Aug 13, 2009, 2:21:31 PM
 */
package net.colar.netbeans.fan.wizard;

/**
 * Main UI panel for project/pod properties
 * @author thibautc
 */
public class FanProjectPropertiesPanel extends javax.swing.JPanel
{

	/** Creates new form FanProjectPropertiesPanel */
	public FanProjectPropertiesPanel()
	{
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMethodLbl = new javax.swing.JLabel();
        buildTargetLbl = new javax.swing.JLabel();
        mainMethod = new javax.swing.JTextField();
        buildTarget = new javax.swing.JTextField();

        mainMethodLbl.setText(org.openide.util.NbBundle.getMessage(FanProjectPropertiesPanel.class, "FanProjectPropertiesPanel.mainMethodLbl.text")); // NOI18N

        buildTargetLbl.setText(org.openide.util.NbBundle.getMessage(FanProjectPropertiesPanel.class, "FanProjectPropertiesPanel.buildTargetLbl.text")); // NOI18N

        mainMethod.setText(org.openide.util.NbBundle.getMessage(FanProjectPropertiesPanel.class, "FanProjectPropertiesPanel.mainMethod.text")); // NOI18N

        buildTarget.setText(org.openide.util.NbBundle.getMessage(FanProjectPropertiesPanel.class, "FanProjectPropertiesPanel.buildTarget.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainMethodLbl)
                    .addComponent(buildTargetLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buildTarget)
                    .addComponent(mainMethod, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainMethodLbl)
                    .addComponent(mainMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildTargetLbl)
                    .addComponent(buildTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buildTarget;
    private javax.swing.JLabel buildTargetLbl;
    private javax.swing.JTextField mainMethod;
    private javax.swing.JLabel mainMethodLbl;
    // End of variables declaration//GEN-END:variables

	public void setBuildTarget(String target)
	{
		if(target==null)
			target="";
		buildTarget.setText(target);
	}
	
	public String getMainMethod()
	{
		return mainMethod.getText();
	}
	public String getBuildTarget()
	{
		return buildTarget.getText();
	}

	public void setMainMethod(String method)
	{
		if(method==null || method.length()==0)
			method="Main.main";
		mainMethod.setText(method);
	}
}
