/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FanPodIndexForm.java
 *
 * Created on Apr 4, 2010, 4:30:25 PM
 */

package net.colar.netbeans.fan.wizard;

import java.util.SortedSet;
import java.util.TreeSet;
import java.util.concurrent.ExecutionException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.*;
import org.openide.util.Exceptions;

/**
 *
 * @author bheadley
 */
public class FanPodIndexForm extends javax.swing.JDialog {

    /** Creates new form FanPodIndexForm */
    public FanPodIndexForm(java.awt.Dialog parent, String title, boolean modal) {
        super(parent, title, modal);
        initComponents();
        localInit();
    }
    private void localInit() {
        indexList.setModel(new DefaultListModel());
        indexList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        keyTextField.setText("");
        valueTextField.setText("");
        setVisible(false);
    }
    public int showDialog(SortedSet<String>indices) {
        setValues(indices);
        returnValue = ERROR_OPTION;
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                returnValue = CANCEL_OPTION;
            }
        });
        setVisible(true);

        this.dispose();
        return returnValue;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keyTextField = new javax.swing.JTextField();
        valueTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        indexList = new javax.swing.JList();
        deleteButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        keyTextField.setText(org.openide.util.NbBundle.getMessage(FanPodIndexForm.class, "FanPodIndexForm.keyTextField.text")); // NOI18N

        valueTextField.setText(org.openide.util.NbBundle.getMessage(FanPodIndexForm.class, "FanPodIndexForm.valueTextField.text")); // NOI18N

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(FanPodIndexForm.class, "FanPodIndexForm.jLabel1.text")); // NOI18N

        addButton.setText(org.openide.util.NbBundle.getMessage(FanPodIndexForm.class, "FanPodIndexForm.addButton.text")); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        indexList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(indexList);

        deleteButton.setText(org.openide.util.NbBundle.getMessage(FanPodIndexForm.class, "FanPodIndexForm.deleteButton.text")); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        finishButton.setText(org.openide.util.NbBundle.getMessage(FanPodIndexForm.class, "FanPodIndexForm.finishButton.text")); // NOI18N
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(org.openide.util.NbBundle.getMessage(FanPodIndexForm.class, "FanPodIndexForm.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(keyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(finishButton)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton)
                    .addComponent(finishButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        final SwingWorker<Integer,Integer> sw = new SwingWorker<Integer,Integer>() {
            @Override
            public Integer doInBackground() {
                final String key = keyTextField.getText();
                final String value = valueTextField.getText();
                if (null == key || "".equals(key) ||
                    null == value || "".equals(value)) {
                    return 0;
                }
                final DefaultListModel model = (DefaultListModel) indexList.getModel();
                model.addElement(key + " : " + value);
                return 0;
            }
        };
        sw.execute();
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        final SwingWorker<Integer,Integer> sw = new SwingWorker<Integer,Integer>() {
            @Override
            public Integer doInBackground() {
                final DefaultListModel model = (DefaultListModel) indexList.getModel();
                int[] indices = indexList.getSelectedIndices();
                for (int i = indices.length-1; i >= 0; i--) {
                    int row = indices[i];
                    model.remove(row);
                }
                return 0;
            }
        };
        sw.execute();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        returnValue = APPROVE_OPTION;
        setVisible(false);
    }//GEN-LAST:event_finishButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        returnValue = CANCEL_OPTION;
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    public void setValues(final SortedSet<String> values) {
        final SwingWorker<Integer,Integer> sw = new SwingWorker<Integer,Integer>() {
            @Override
            public Integer doInBackground() {
                final DefaultListModel model = (DefaultListModel) indexList.getModel();
                model.clear();
                int i = 0;
                for (String str : values) {
                    model.add(i, str);
                    i++;
                }
                return 0;
            }
        };
        sw.execute();
    }
    public SortedSet<String> getValues() {
        final SortedSet<String> set = new TreeSet<String>();
        final SwingWorker<Integer,Integer> sw = new SwingWorker<Integer,Integer>() {
            @Override
            public Integer doInBackground() {
                final DefaultListModel model = (DefaultListModel) indexList.getModel();
                for (int i = 0; i < model.getSize(); i++) {
                    set.add(model.get(i).toString());
                }
                return 0;
            }
        };
        sw.execute();
        // wait for return code.
        try {
            sw.get();
        } catch (InterruptedException ex) {
            Exceptions.printStackTrace(ex);
        } catch (ExecutionException ex) {
            Exceptions.printStackTrace(ex);
        }
        return set;
    }

    public static final int CANCEL_OPTION = 1;
    public static final int APPROVE_OPTION = 0;
    public static final int ERROR_OPTION = -1;
    private int returnValue = ERROR_OPTION;

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JList indexList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keyTextField;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables

}
