/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FanPodDependencyPanel.java
 *
 * Created on Apr 6, 2010, 1:09:54 PM
 */

package net.colar.netbeans.fan.wizard;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;
import java.io.File;
import java.io.FilenameFilter;
import java.util.SortedSet;
import java.util.TreeSet;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.*;
import java.awt.*;
import net.colar.netbeans.fan.utils.DependencyPair;

/**
 *
 * @author bheadley
 */
public class FanPodDependencyPanel extends javax.swing.JDialog {

    /** Creates new form FanPodDependencyPanel */
    public FanPodDependencyPanel(java.awt.Frame parent, String title) {
        super(parent, title, true);
        initComponents();
    }
    public FanPodDependencyPanel(java.awt.Dialog parent, String title) {
        super(parent, title, true);
        initComponents();
    }
    public int showDialog(final File[] directories, final SortedSet<DependencyPair> selected)
        throws HeadlessException {
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                returnValue = CANCEL_OPTION;
            }
        });
        returnValue = ERROR_OPTION;
        selected.addAll(selected);
        localInit(directories);

        setVisible(true);

        dispose();
        return returnValue;
    }
    private void localInit(final File[] directories) {
        systemPodList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        userPodList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        // Do a directory
        initDependencyList(systemPodList, directories[0]);
        initDependencyList(userPodList, directories.length > 1 ? directories[1] : null);

        // populate the text field with selected pods
        selectedToTextField();

        // set up listeners to keep text field && selected populated with
        // currently selected pods
        systemPodList.addListSelectionListener(new OurListSelectionListener());
        userPodList.addListSelectionListener(new OurListSelectionListener());
        this.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        systemPodList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        userPodList = new javax.swing.JList();
        dependenciesField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FanPodDependencyPanel.class, "FanPodDependencyPanel.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(FanPodDependencyPanel.class, "FanPodDependencyPanel.jLabel2.text")); // NOI18N

        systemPodList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(systemPodList);

        userPodList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(userPodList);

        dependenciesField.setText(org.openide.util.NbBundle.getMessage(FanPodDependencyPanel.class, "FanPodDependencyPanel.dependenciesField.text_1")); // NOI18N

        cancelButton.setMnemonic('C');
        cancelButton.setText(org.openide.util.NbBundle.getMessage(FanPodDependencyPanel.class, "FanPodDependencyPanel.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        finishButton.setMnemonic('F');
        finishButton.setText(org.openide.util.NbBundle.getMessage(FanPodDependencyPanel.class, "FanPodDependencyPanel.finishButton.text")); // NOI18N
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dependenciesField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 177, Short.MAX_VALUE)
                        .add(jLabel2))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(cancelButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 273, Short.MAX_VALUE)
                        .add(finishButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(dependenciesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(finishButton)
                    .add(cancelButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        returnValue = CANCEL_OPTION;
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        returnValue = APPROVE_OPTION;
        setVisible(false);
    }//GEN-LAST:event_finishButtonActionPerformed
    private void initDependencyList(final javax.swing.JList list, final File rootDir) {
        final SwingWorker<Integer,Integer> sw = new SwingWorker<Integer,Integer>() {
            @Override
            public Integer doInBackground() {
                final DefaultListModel model = (DefaultListModel) list.getModel();
                model.clear();
                if (rootDir != null && rootDir.exists() && rootDir.isDirectory() ) {
                    final File[] files = rootDir.listFiles(new FilenameFilter() {
                        @Override
                        public boolean accept(File file, String name) {
                            final int offset = name.lastIndexOf('.');
                            if (offset == -1) {
                                return false;
                            }
                            final String extension = name.substring(offset);
                            if (".pod".equalsIgnoreCase(extension)) {
                                return true;
                            }
                            return false;
                        }
                    });
                    if (null != files) {
                        for (int i = 0; i < files.length; i++) {
                            final String s = getPodShortDescription(files[i]);
                            model.add(i,s);
                            final String[] pair = s.split(" ");
                            final DependencyPair d = new DependencyPair(pair[0], pair[1]);
                            if (selected.contains(d)) {
                                list.setSelectedIndex(i);
                            }
                        }
                    }
                }
                return 0;
            }
        };
        sw.execute();
    }
    class OurListSelectionListener implements ListSelectionListener {
        @Override
        public void valueChanged(ListSelectionEvent event) {
            SwingWorker<Integer,Integer> sw = new SwingWorker<Integer,Integer>() {
                @Override
                public Integer doInBackground() {
                    selected.clear();
                    final javax.swing.JList[] lists = {systemPodList,userPodList};
                    for (int i = 0; i < lists.length; i++) {
                        final Object[] selections = lists[i].getSelectedValues();
                        for (int j = 0; j < selections.length; j++) {
                            final String s = selections[j].toString();
                            final String[] pair = s.split(" ");
                            final DependencyPair d = new DependencyPair(pair[0], pair[1]);
                            selected.add(d);
                        }
                    }
                    FanPodDependencyPanel.this.selectedToTextField();
                    return 0;
                }
            };
            sw.execute();
        }
    }
    public void selectedToTextField() {
        final SwingWorker<Integer,Integer> sw = new SwingWorker<Integer,Integer>() {
            @Override
            public Integer doInBackground() {
                final StringBuilder sb = new StringBuilder();
                for (final DependencyPair str : selected) {
                    if (sb.length() != 0) {
                        sb.append(", ");
                    }
                    sb.append("\"");
                    sb.append(str.getPodName());
                    sb.append(' ');
                    sb.append(str.getVersion());
                    sb.append("\"");
                }
                dependenciesField.setText(sb.toString());
                return 0;
            }
        };
        sw.execute();
    }
    public SortedSet<DependencyPair> getSelected() {
        final SortedSet<DependencyPair> s = new TreeSet<DependencyPair>();
        s.addAll(selected);
        return s;
    }
    public String getPodShortDescription(File f) {
        String version = "";
        String podName = "";
        boolean hasVersion = false;
        boolean hasName = false;
        ZipFile zipFile = null;
        BufferedReader is = null;
        try {
            zipFile = new ZipFile(f.getPath());
            ZipEntry zipEntry = zipFile.getEntry("meta.props");
            if (zipEntry == null) {
                return "";
            }
            is = new BufferedReader(new InputStreamReader(
                    zipFile.getInputStream(zipEntry)));
            while (true) {
                final String line = is.readLine();
                if (line.startsWith("pod.version")) {
                    final String[] tokens = line.split("=");
                    version = tokens[1].trim();
                    hasVersion = true;
                }
                else if (line.startsWith("pod.name")) {
                    final String[] tokens = line.split("=");
                    podName = tokens[1].trim();
                    hasName = true;
                }
                if (hasName && hasVersion) {
                    return podName + " " + version ;
                }
            }
        }
        catch (IOException e) {
            e.printStackTrace();
        }
        finally {
            if (null != is) {
                try {is.close();} catch (Exception e1) {e1.printStackTrace();}
            }
            if (null != zipFile) {
                try {zipFile.close();} catch (Exception e1) {e1.printStackTrace();}
            }
        }
        return "";
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dependenciesField;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList systemPodList;
    private javax.swing.JList userPodList;
    // End of variables declaration//GEN-END:variables

    private final SortedSet<DependencyPair> selected = new TreeSet<DependencyPair>();
    public static final int CANCEL_OPTION = 1;
    public static final int APPROVE_OPTION = 0;
    public static final int ERROR_OPTION = -1;
    private int returnValue = ERROR_OPTION;

}
