/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.colar.netbeans.fan.wizard;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

public final class NewFileVisualPanel1 extends JPanel
{

    private NewFileWizardPanel1 parentWizard;
    private JFileChooser chooser;

    /** Creates new form NewFileVisualPanel1 */
    public NewFileVisualPanel1(NewFileWizardPanel1 parent, String dir)
    {
        super();
        this.parentWizard = parent;
        initComponents();
        nameField.setText("");
        folderField.setText(dir);
        String loc = dir + (dir.endsWith(File.separator) ? "" : File.separator);
        fileField.setText(loc);
        chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setApproveButtonText("Select");
    }

    @Override
    public String getName()
    {
        return "Step #1";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        folderLabel = new javax.swing.JLabel();
        folderField = new javax.swing.JTextField();
        fileField = new javax.swing.JTextField();
        fileLabel = new javax.swing.JLabel();
        customLabel = new javax.swing.JLabel();
        customCombo = new javax.swing.JComboBox();
        browseButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        extField = new javax.swing.JTextField();

        nameField.setText(org.openide.util.NbBundle.getMessage(NewFileVisualPanel1.class, "NewFileVisualPanel1.nameField.text")); // NOI18N
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameFieldKeyReleased(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(NewFileVisualPanel1.class, "NewFileVisualPanel1.nameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(folderLabel, org.openide.util.NbBundle.getMessage(NewFileVisualPanel1.class, "NewFileVisualPanel1.folderLabel.text")); // NOI18N

        folderField.setText(org.openide.util.NbBundle.getMessage(NewFileVisualPanel1.class, "NewFileVisualPanel1.folderField.text")); // NOI18N
        folderField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                folderFieldKeyReleased(evt);
            }
        });

        fileField.setEditable(false);
        fileField.setText(org.openide.util.NbBundle.getMessage(NewFileVisualPanel1.class, "NewFileVisualPanel1.fileField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(fileLabel, org.openide.util.NbBundle.getMessage(NewFileVisualPanel1.class, "NewFileVisualPanel1.fileLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(customLabel, org.openide.util.NbBundle.getMessage(NewFileVisualPanel1.class, "NewFileVisualPanel1.customLabel.text")); // NOI18N

        customCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Add Empty Class", "Add Class with main method", "Add Mixin", "Add Enum", "Leave Empty" }));

        org.openide.awt.Mnemonics.setLocalizedText(browseButton, org.openide.util.NbBundle.getMessage(NewFileVisualPanel1.class, "NewFileVisualPanel1.browseButton.text")); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        org.openide.awt.Mnemonics.setLocalizedText(errorLabel, org.openide.util.NbBundle.getMessage(NewFileVisualPanel1.class, "NewFileVisualPanel1.errorLabel.text")); // NOI18N

        extField.setText(org.openide.util.NbBundle.getMessage(NewFileVisualPanel1.class, "NewFileVisualPanel1.extField.text")); // NOI18N
        extField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                extFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customLabel)
                            .addComponent(nameLabel)
                            .addComponent(folderLabel)
                            .addComponent(fileLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addComponent(customCombo, 0, 329, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(folderField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(extField, 0, 0, Short.MAX_VALUE)
                                    .addComponent(browseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folderLabel)
                    .addComponent(folderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customLabel)
                    .addComponent(customCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nameFieldKeyReleased
    {//GEN-HEADEREND:event_nameFieldKeyReleased
        updateFile();
    }//GEN-LAST:event_nameFieldKeyReleased

    private void folderFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_folderFieldKeyReleased
    {//GEN-HEADEREND:event_folderFieldKeyReleased
        updateFile();
    }//GEN-LAST:event_folderFieldKeyReleased

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_browseButtonActionPerformed
    {//GEN-HEADEREND:event_browseButtonActionPerformed
        int val = chooser.showDialog(this, "Select");
        if (val == JFileChooser.APPROVE_OPTION)
        {
            folderField.setText(chooser.getSelectedFile().getPath());
            updateFile();
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void extFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_extFieldKeyReleased
    {//GEN-HEADEREND:event_extFieldKeyReleased
        updateFile();
    }//GEN-LAST:event_extFieldKeyReleased

    @Override
    public boolean isValid()
    {
        if (errorLabel == null)
        {
            return false;
        }
        
        String loc = folderField.getText();
        String file = fileField.getText();
        String name = nameField.getText();

        if (loc == null || loc.length() < 1)
        {
            errorLabel.setText("Please choose a location.");
            return false;
        }
        File locF = new File(loc);
        
        if (name.isEmpty())
        {
            errorLabel.setText("Please enter a project name.");
            return false;
        }
        if (name.indexOf(".") != -1)
        {
            errorLabel.setText("Invalid characters in the project name.");
            return false;
        }
        if (extField.getText().indexOf(".") != 0)
        {
            errorLabel.setText("File extension missing.");
            return false;
        }
        if (!locF.exists() || !locF.isDirectory() || !locF.canWrite())
        {
            errorLabel.setText("Folder must be an existing, writable directory.");
            return false;
        }
        if (!checkName(name))
        {
            errorLabel.setText("Please enter a valid name.");
            return false;
        }
        if (new File(file).exists())
        {
            errorLabel.setText("This file already exists.");
            return false;
        }

        errorLabel.setText("");
        return true;
    }

    private void updateFile()
    {
        String dir = folderField.getText();
        dir += (dir.endsWith(File.separator) ? "" : File.separator) + nameField.getText() + extField.getText();
        fileField.setText(dir);
        // will recheck that it's valid
        parentWizard.fireChangeEvent();
    }

    private boolean checkName(String text)
    {
        return FanPodPanel1.VALID_NAME.matcher(text).matches();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JComboBox customCombo;
    private javax.swing.JLabel customLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField extField;
    private javax.swing.JTextField fileField;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JTextField folderField;
    private javax.swing.JLabel folderLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

    String getFile()
    {
        return fileField.getText();
    }

    int getComboChoice()
    {
        return customCombo.getSelectedIndex();
    }

    String getFileName()
    {
        return nameField.getText();
    }
}
